=== jafansari/sumo-complete/sumo/docs/internet/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"></xsd:selector>
            <xsd:field xpath="@id"></xsd:field>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"></xsd:selector>
            <xsd:field xpath="@from"></xsd:field>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"></xsd:selector>
            <xsd:field xpath="@to"></xsd:field>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"></xsd:element>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="locationType">
        <xsd:attribute name="netOffset">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="convBoundary">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="origBoundary">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="projParameter" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:sequence>
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="internal"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="to" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"></xsd:attribute>
        <xsd:attribute name="type" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="shape" type="shapeType" use="optional"></xsd:attribute>
        <xsd:attribute name="spreadType" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="center"></xsd:enumeration>
                    <xsd:enumeration value="right"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="laneType">
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
        <xsd:attribute name="allow" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"></xsd:attribute>
        <xsd:attribute name="length" type="positiveFloatType" use="required"></xsd:attribute>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"></xsd:attribute>
        <xsd:attribute name="width" type="positiveFloatType" use="optional"></xsd:attribute>
        <xsd:attribute name="shape" type="shapeType" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tlLogicType">
        <xsd:sequence>
            <xsd:element name="phase" type="phaseType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="actuated"></xsd:enumeration>
                    <xsd:enumeration value="agentbased"></xsd:enumeration>
                    <xsd:enumeration value="static"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="programID" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="offset" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="phaseType">
        <xsd:attribute name="duration" type="positiveFloatType" use="required"></xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[ryYgGoO]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="x" type="xsd:float" use="required"></xsd:attribute>
        <xsd:attribute name="y" type="xsd:float" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"></xsd:enumeration>
                    <xsd:enumeration value="right_before_left"></xsd:enumeration>
                    <xsd:enumeration value="priority"></xsd:enumeration>
                    <xsd:enumeration value="dead_end"></xsd:enumeration>
                    <xsd:enumeration value="unregulated"></xsd:enumeration>
                    <xsd:enumeration value="internal"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="shape" type="shapeType" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="xsd:boolean" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:attribute name="from" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="to" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"></xsd:attribute>
        <xsd:attribute name="via" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="tl" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="linkIndex" type="xsd:nonNegativeInteger" use="optional"></xsd:attribute>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"></xsd:enumeration>
                    <xsd:enumeration value="t"></xsd:enumeration>
                    <xsd:enumeration value="l"></xsd:enumeration>
                    <xsd:enumeration value="r"></xsd:enumeration>
                    <xsd:enumeration value="L"></xsd:enumeration>
                    <xsd:enumeration value="R"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"></xsd:enumeration>
                    <xsd:enumeration value="m"></xsd:enumeration>
                    <xsd:enumeration value="o"></xsd:enumeration>
                    <xsd:enumeration value="="></xsd:enumeration>
                    <xsd:enumeration value="-"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tazType">
        <xsd:sequence>
            <xsd:element name="tazSource" type="tazSourceType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="tazSink" type="tazSinkType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="shape" type="shapeType" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tazSourceType">
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="weight" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tazSinkType">
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="weight" type="xsd:float" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="shapeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern
                value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))(\s(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)))+">
            </xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="positiveFloatType">
        <xsd:restriction base="xsd:float">
            <xsd:minExclusive value="0"></xsd:minExclusive>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== jafansari/sumo-complete/sumo/tools/projects/TLS-Evaluationsszenarien/sumoConfig/one_intersection/cross.net.xml
<?xml version="1.0" ?><!-- generated on Tue May  7 15:49:11 2013 by SUMO netconvert Version dev-SVN-rUNKNOWN
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="./tools/projects/TLS-Evaluationsszenarien/sumoConfig/one_intersection/cross.nod.xml"/>
        <edge-files value="./tools/projects/TLS-Evaluationsszenarien/sumoConfig/one_intersection/cross.edg.xml"/>
        <connection-files value="./tools/projects/TLS-Evaluationsszenarien/sumoConfig/one_intersection/cross.con.xml"/>
    </input>

    <output>
        <output-file value="./tools/projects/TLS-Evaluationsszenarien/sumoConfig/one_intersection/cross.net.xml"/>
    </output>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
--><net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/net_file.xsd">

    <location convBoundary="0.00,0.00,1020.00,1020.00" netOffset="510.00,510.00" origBoundary="-510.00,-510.00,510.00,510.00" projParameter="!"/>

    <edge function="internal" id=":0_0">
        <lane id=":0_0_0" index="0" length="9.50" shape="508.35,514.75 508.35,505.25" speed="16.67"/>
    </edge>
    <edge function="internal" id=":0_1">
        <lane id=":0_1_0" index="0" length="9.50" shape="514.75,511.65 505.25,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":0_2">
        <lane id=":0_2_0" index="0" length="9.50" shape="511.65,505.25 511.65,514.75" speed="16.67"/>
    </edge>
    <edge function="internal" id=":0_3">
        <lane id=":0_3_0" index="0" length="9.50" shape="505.25,508.35 514.75,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_0">
        <lane id=":1_0_0" index="0" length="0.10" shape="10.00,511.65 10.00,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_1">
        <lane id=":1_1_0" index="0" length="2.41" shape="10.00,511.65 8.76,510.82 8.35,510.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_4">
        <lane id=":1_4_0" index="0" length="2.41" shape="8.35,510.00 8.76,509.18 10.00,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_2">
        <lane id=":1_2_0" index="0" length="0.10" shape="10.00,508.35 10.00,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_3">
        <lane id=":1_3_0" index="0" length="2.41" shape="10.00,508.35 11.24,509.18 11.65,510.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":1_5">
        <lane id=":1_5_0" index="0" length="2.41" shape="11.65,510.00 11.24,510.82 10.00,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_0">
        <lane id=":2_0_0" index="0" length="0.10" shape="1010.00,511.65 1010.00,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_1">
        <lane id=":2_1_0" index="0" length="2.41" shape="1010.00,511.65 1008.76,510.82 1008.35,510.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_4">
        <lane id=":2_4_0" index="0" length="2.41" shape="1008.35,510.00 1008.76,509.18 1010.00,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_2">
        <lane id=":2_2_0" index="0" length="0.10" shape="1010.00,508.35 1010.00,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_3">
        <lane id=":2_3_0" index="0" length="2.41" shape="1010.00,508.35 1011.24,509.18 1011.65,510.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":2_5">
        <lane id=":2_5_0" index="0" length="2.41" shape="1011.65,510.00 1011.24,510.82 1010.00,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_0">
        <lane id=":3_0_0" index="0" length="0.10" shape="508.35,10.00 508.35,10.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_1">
        <lane id=":3_1_0" index="0" length="2.41" shape="508.35,10.00 509.18,8.76 510.00,8.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_4">
        <lane id=":3_4_0" index="0" length="2.41" shape="510.00,8.35 510.82,8.76 511.65,10.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_2">
        <lane id=":3_2_0" index="0" length="0.10" shape="511.65,10.00 511.65,10.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_3">
        <lane id=":3_3_0" index="0" length="2.41" shape="511.65,10.00 510.82,11.24 510.00,11.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":3_5">
        <lane id=":3_5_0" index="0" length="2.41" shape="510.00,11.65 509.18,11.24 508.35,10.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_0">
        <lane id=":4_0_0" index="0" length="0.10" shape="508.35,1010.00 508.35,1010.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_1">
        <lane id=":4_1_0" index="0" length="2.41" shape="508.35,1010.00 509.18,1008.76 510.00,1008.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_4">
        <lane id=":4_4_0" index="0" length="2.41" shape="510.00,1008.35 510.82,1008.76 511.65,1010.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_2">
        <lane id=":4_2_0" index="0" length="0.10" shape="511.65,1010.00 511.65,1010.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_3">
        <lane id=":4_3_0" index="0" length="2.41" shape="511.65,1010.00 510.82,1011.24 510.00,1011.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":4_5">
        <lane id=":4_5_0" index="0" length="2.41" shape="510.00,1011.65 509.18,1011.24 508.35,1010.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":51_0">
        <lane id=":51_0_0" index="0" length="4.82" shape="0.00,511.65 -1.24,510.82 -1.65,510.00 -1.24,509.18 0.00,508.35" speed="16.67"/>
    </edge>
    <edge function="internal" id=":52_0">
        <lane id=":52_0_0" index="0" length="4.82" shape="1020.00,508.35 1021.24,509.18 1021.65,510.00 1021.24,510.82 1020.00,511.65" speed="16.67"/>
    </edge>
    <edge function="internal" id=":53_0">
        <lane id=":53_0_0" index="0" length="4.82" shape="508.35,0.00 509.18,-1.24 510.00,-1.65 510.82,-1.24 511.65,0.00" speed="16.67"/>
    </edge>
    <edge function="internal" id=":54_0">
        <lane id=":54_0_0" index="0" length="4.82" shape="511.65,1020.00 510.82,1021.24 510.00,1021.65 509.18,1021.24 508.35,1020.00" speed="16.67"/>
    </edge>

    <edge from="1" id="1i" priority="78" to="0">
        <lane id="1i_0" index="0" length="495.25" shape="10.00,508.35 505.25,508.35" speed="16.67"/>
    </edge>
    <edge from="0" id="1o" priority="46" to="1">
        <lane id="1o_0" index="0" length="495.25" shape="505.25,511.65 10.00,511.65" speed="16.67"/>
    </edge>
    <edge from="2" id="2i" priority="78" to="0">
        <lane id="2i_0" index="0" length="495.25" shape="1010.00,511.65 514.75,511.65" speed="16.67"/>
    </edge>
    <edge from="0" id="2o" priority="46" to="2">
        <lane id="2o_0" index="0" length="495.25" shape="514.75,508.35 1010.00,508.35" speed="16.67"/>
    </edge>
    <edge from="3" id="3i" priority="78" to="0">
        <lane id="3i_0" index="0" length="495.25" shape="511.65,10.00 511.65,505.25" speed="16.67"/>
    </edge>
    <edge from="0" id="3o" priority="46" to="3">
        <lane id="3o_0" index="0" length="495.25" shape="508.35,505.25 508.35,10.00" speed="16.67"/>
    </edge>
    <edge from="4" id="4i" priority="78" to="0">
        <lane id="4i_0" index="0" length="495.25" shape="508.35,1010.00 508.35,514.75" speed="16.67"/>
    </edge>
    <edge from="0" id="4o" priority="46" to="4">
        <lane id="4o_0" index="0" length="495.25" shape="511.65,514.75 511.65,1010.00" speed="16.67"/>
    </edge>
    <edge from="1" id="51i" priority="78" to="51">
        <lane id="51i_0" index="0" length="10.00" shape="10.00,511.65 0.00,511.65" speed="16.67"/>
    </edge>
    <edge from="51" id="51o" priority="46" to="1">
        <lane id="51o_0" index="0" length="10.00" shape="0.00,508.35 10.00,508.35" speed="16.67"/>
    </edge>
    <edge from="2" id="52i" priority="78" to="52">
        <lane id="52i_0" index="0" length="10.00" shape="1010.00,508.35 1020.00,508.35" speed="16.67"/>
    </edge>
    <edge from="52" id="52o" priority="46" to="2">
        <lane id="52o_0" index="0" length="10.00" shape="1020.00,511.65 1010.00,511.65" speed="16.67"/>
    </edge>
    <edge from="3" id="53i" priority="78" to="53">
        <lane id="53i_0" index="0" length="10.00" shape="508.35,10.00 508.35,0.00" speed="16.67"/>
    </edge>
    <edge from="53" id="53o" priority="46" to="3">
        <lane id="53o_0" index="0" length="10.00" shape="511.65,0.00 511.65,10.00" speed="16.67"/>
    </edge>
    <edge from="4" id="54i" priority="78" to="54">
        <lane id="54i_0" index="0" length="10.00" shape="511.65,1010.00 511.65,1020.00" speed="16.67"/>
    </edge>
    <edge from="54" id="54o" priority="46" to="4">
        <lane id="54o_0" index="0" length="10.00" shape="508.35,1020.00 508.35,1010.00" speed="16.67"/>
    </edge>

    <tlLogic id="0" offset="0" programID="0" type="actuated">
        <phase duration="6" maxDur="120" minDur="6" state="GrGr"/>
        <phase duration="5" state="yryr"/>
        <phase duration="6" maxDur="120" minDur="6" state="rGrG"/>
        <phase duration="5" state="ryry"/>
    </tlLogic>

    <junction id="0" incLanes="4i_0 2i_0 3i_0 1i_0" intLanes=":0_0_0 :0_1_0 :0_2_0 :0_3_0" shape="506.75,514.75 513.25,514.75 514.75,513.25 514.75,506.75 513.25,505.25 506.75,505.25 505.25,506.75 505.25,513.25" type="traffic_light" x="510.00" y="510.00">
        <request cont="0" foes="1010" index="0" response="0000"/>
        <request cont="0" foes="0101" index="1" response="0101"/>
        <request cont="0" foes="1010" index="2" response="0000"/>
        <request cont="0" foes="0101" index="3" response="0101"/>
    </junction>
