=== jafansari/sumo-complete/docs/internet/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="net" type="netType"></xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"></xsd:element>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="\d+.\d+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="locationType">
        <xsd:attribute name="netOffset">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="convBoundary">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="origBoundary">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="projParameter" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:sequence>
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="internal"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="to" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="priority" type="xsd:int" use="optional"></xsd:attribute>
        <xsd:attribute name="type" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="shape" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))(\s(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)))+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="spreadType" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="center"></xsd:enumeration>
                    <xsd:enumeration value="right"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="laneType">
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="index" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="maxSpeed" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:float">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="allow" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="length" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:float">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="shape" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))(\s(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)))+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tlLogicType">
        <xsd:sequence>
            <xsd:element name="phase" type="phaseType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="actuated"></xsd:enumeration>
                    <xsd:enumeration value="agentbased"></xsd:enumeration>
                    <xsd:enumeration value="static"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="programID" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="offset" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:float">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="phaseType">
        <xsd:attribute name="duration" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:float">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[ryYgGoO]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="x" type="xsd:float" use="required"></xsd:attribute>
        <xsd:attribute name="y" type="xsd:float" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"></xsd:enumeration>
                    <xsd:enumeration value="right_before_left"></xsd:enumeration>
                    <xsd:enumeration value="priority"></xsd:enumeration>
                    <xsd:enumeration value="dead_end"></xsd:enumeration>
                    <xsd:enumeration value="unregulated"></xsd:enumeration>
                    <xsd:enumeration value="internal"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="shape" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="((\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))(\s(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)))+)?">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="0"></xsd:enumeration>
                    <xsd:enumeration value="1"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:attribute name="from" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="to" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="fromLane" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="toLane" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="via" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="tl" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="linkIndex" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"></xsd:enumeration>
                    <xsd:enumeration value="r"></xsd:enumeration>
                    <xsd:enumeration value="l"></xsd:enumeration>
                    <xsd:enumeration value="t"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"></xsd:enumeration>
                    <xsd:enumeration value="m"></xsd:enumeration>
                    <xsd:enumeration value="o"></xsd:enumeration>
                    <xsd:enumeration value="="></xsd:enumeration>
                    <xsd:enumeration value="-"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== jafansari/sumo-complete/tests/sumo/model/jam_resolution/bottleneck_confluence/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Oct  4 15:30:19 2012 by SUMO netconvert Version dev-SVN-r12771
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/netconvertConfiguration.xsd">

    <input>
        <sumo-net-file value="bottleneck.net.xml"/>
    </input>

    <output>
        <output-file value="net.net.xml"/>
    </output>

    <processing>
        <no-internal-links value="true"/>
        <no-turnarounds value="true"/>
        <offset.disable-normalization value="true"/>
    </processing>

</configuration>
-->

<net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-500.00,-100.00,500.00,100.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id="in1" from="gneJ0" to="gneJ1" priority="1">
        <lane id="in1_0" index="0" speed="13.89" length="500.73" shape="-500.32,98.38 -9.32,0.18"/>
    </edge>
    <edge id="in2" from="gneJ2" to="gneJ1" priority="1">
        <lane id="in2_0" index="0" speed="13.89" length="500.07" shape="-499.68,-101.62 -9.32,-3.55"/>
    </edge>
    <edge id="out" from="gneJ1" to="gneJ3" priority="1">
        <lane id="out_0" index="0" speed="13.89" length="498.50" shape="1.50,-1.65 500.00,-1.65"/>
    </edge>

    <junction id="gneJ0" type="unregulated" x="-500.00" y="100.00" incLanes="" intLanes="" shape="-500.01,99.95 -500.64,96.81">
    </junction>
    <junction id="gneJ1" type="priority" x="0.00" y="0.00" incLanes="in2_0 in1_0" intLanes="" shape="1.50,-0.05 1.50,-3.25 -9.00,-5.11 -9.63,-1.98 -9.63,-1.39 -9.00,1.75">
        <request index="0" response="00" foes="10"/>
        <request index="1" response="01" foes="01"/>
    </junction>
    <junction id="gneJ2" type="unregulated" x="-500.00" y="-100.00" incLanes="" intLanes="" shape="-499.99,-100.05 -499.36,-103.19">
    </junction>
    <junction id="gneJ3" type="unregulated" x="500.00" y="0.00" incLanes="out_0" intLanes="" shape="500.00,-3.25 500.00,-0.05">
    </junction>

    <connection from="in1" to="out" fromLane="0" toLane="0" dir="s" state="m"/>
    <connection from="in2" to="out" fromLane="0" toLane="0" dir="s" state="M"/>

</net>

=== jafansari/sumo-complete/tests/sumo/basic/person/pedestrian/pedestrian_interactions/jam_trafficlight/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Jan 16 10:42:00 2014 by SUMO netconvert Version dev-SVN-r15378
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo-sim.org/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="plain3b.nod.xml"/>
        <edge-files value="plain3b.edg.xml"/>
        <connection-files value="plain3b.con.xml"/>
        <tllogic-files value="plain3b.tll.xml"/>
    </input>

    <output>
        <output-file value="net3b.net.xml"/>
    </output>

    <processing>
        <no-turnarounds value="true"/>
    </processing>

</configuration>
-->

<net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo-sim.org/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="0.00,0.00,80.00,0.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id=":gneJ1_0" function="internal">
        <lane id=":gneJ1_0_0" index="0" allow="pedestrian" speed="13.89" length="0.10" width="2.50" shape="20.00,-6.40 20.00,-6.40"/>
    </edge>
    <edge id=":gneJ2_0" function="internal">
        <lane id=":gneJ2_0_0" index="0" allow="pedestrian" speed="13.89" length="0.10" width="2.50" shape="40.00,-6.40 40.00,-6.40"/>
    </edge>
    <edge id=":gneJ3_0" function="internal">
        <lane id=":gneJ3_0_0" index="0" allow="pedestrian" speed="13.89" length="0.10" width="2.50" shape="60.00,-6.40 60.00,-6.40"/>
    </edge>

    <edge id="A" from="gneJ0" to="gneJ1" priority="1">
        <lane id="A_0" index="0" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="0.00,-10.25 20.00,-10.25"/>
        <lane id="A_1" index="1" allow="pedestrian" speed="13.89" length="20.00" width="2.50" shape="0.00,-6.40 20.00,-6.40"/>
        <lane id="A_2" index="2" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="0.00,-2.55 20.00,-2.55"/>
    </edge>
    <edge id="B" from="gneJ1" to="gneJ2" priority="1">
        <lane id="B_0" index="0" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="20.00,-10.25 40.00,-10.25"/>
        <lane id="B_1" index="1" allow="pedestrian" speed="13.89" length="20.00" width="2.50" shape="20.00,-6.40 40.00,-6.40"/>
        <lane id="B_2" index="2" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="20.00,-2.55 40.00,-2.55"/>
    </edge>
    <edge id="C" from="gneJ2" to="gneJ3" priority="1">
        <lane id="C_0" index="0" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="40.00,-10.25 60.00,-10.25"/>
        <lane id="C_1" index="1" allow="pedestrian" speed="13.89" length="20.00" width="2.50" shape="40.00,-6.40 60.00,-6.40"/>
        <lane id="C_2" index="2" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="40.00,-2.55 60.00,-2.55"/>
    </edge>
    <edge id="D" from="gneJ3" to="gneJ5" priority="1">
        <lane id="D_0" index="0" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="60.00,-10.25 80.00,-10.25"/>
        <lane id="D_1" index="1" allow="pedestrian" speed="13.89" length="20.00" width="2.50" shape="60.00,-6.40 80.00,-6.40"/>
        <lane id="D_2" index="2" disallow="private public_transport public_emergency public_authority public_army vip ignoring passenger hov taxi bus delivery transport lightrail cityrail rail_slow rail_fast motorcycle bicycle pedestrian custom1 custom2" speed="13.89" length="20.00" width="5.00" shape="60.00,-2.55 80.00,-2.55"/>
    </edge>

    <tlLogic id="gneJ2" type="static" programID="0" offset="0">
        <phase duration="30" state="G"/>
        <phase duration="30" state="r"/>
    </tlLogic>

    <junction id="gneJ0" type="unregulated" x="0.00" y="0.00" incLanes="" intLanes="" shape="-0.00,-0.95 -0.00,-11.85"/>
    <junction id="gneJ1" type="priority" x="20.00" y="0.00" incLanes="A_0 A_1 A_2" intLanes=":gneJ1_0_0" shape="20.00,-0.95 20.00,-11.85 20.00,-0.95">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="gneJ2" type="traffic_light" x="40.00" y="0.00" incLanes="B_0 B_1 B_2" intLanes=":gneJ2_0_0" shape="40.00,-0.95 40.00,-11.85 40.00,-0.95">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="gneJ3" type="priority" x="60.00" y="0.00" incLanes="C_0 C_1 C_2" intLanes=":gneJ3_0_0" shape="60.00,-0.95 60.00,-11.85 60.00,-0.95">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="gneJ5" type="unregulated" x="80.00" y="0.00" incLanes="D_0 D_1 D_2" intLanes="" shape="80.00,-11.85 80.00,-0.95"/>

    <connection from="A" to="B" fromLane="1" toLane="1" via=":gneJ1_0_0" dir="s" state="M"/>
    <connection from="B" to="C" fromLane="1" toLane="1" via=":gneJ2_0_0" tl="gneJ2" linkIndex="0" dir="s" state="o"/>
    <connection from="C" to="D" fromLane="1" toLane="1" via=":gneJ3_0_0" dir="s" state="M"/>

    <connection from=":gneJ1_0" to="B" fromLane="0" toLane="1" dir="s" state="M"/>
    <connection from=":gneJ2_0" to="C" fromLane="0" toLane="1" dir="s" state="M"/>
    <connection from=":gneJ3_0" to="D" fromLane="0" toLane="1" dir="s" state="M"/>

</net>
